/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LoginImport } from './routes/login'
import { Route as AuthedImport } from './routes/_authed'
import { Route as IndexImport } from './routes/index'
import { Route as AuthedDashboardImport } from './routes/_authed/dashboard'
import { Route as AuthedDashboardIndexImport } from './routes/_authed/dashboard/index'
import { Route as AuthedDashboardSettingsImport } from './routes/_authed/dashboard/settings'
import { Route as AuthedDashboardProjectIndexImport } from './routes/_authed/dashboard/project/index'
import { Route as AuthedDashboardDatasetIndexImport } from './routes/_authed/dashboard/dataset/index'
import { Route as AuthedDashboardProjectCreateImport } from './routes/_authed/dashboard/project/create'
import { Route as AuthedDashboardProjectProjectIdImport } from './routes/_authed/dashboard/project/$projectId'
import { Route as AuthedDashboardDatasetCreateImport } from './routes/_authed/dashboard/dataset/create'
import { Route as AuthedDashboardDatasetDatasetIdImport } from './routes/_authed/dashboard/dataset/$datasetId'
import { Route as AuthedDashboardProjectProjectIdIndexImport } from './routes/_authed/dashboard/project/$projectId/index'
import { Route as AuthedDashboardProjectProjectIdCompareImport } from './routes/_authed/dashboard/project/$projectId/compare'
import { Route as AuthedDashboardProjectProjectIdInferenceCreateImport } from './routes/_authed/dashboard/project/$projectId/inference/create'
import { Route as AuthedDashboardProjectProjectIdInferenceInferenceIdIndexImport } from './routes/_authed/dashboard/project/$projectId/inference/$inferenceId/index'
import { Route as AuthedDashboardProjectProjectIdInferenceInferenceIdEvaluationIndexImport } from './routes/_authed/dashboard/project/$projectId/inference/$inferenceId/evaluation/index'
import { Route as AuthedDashboardProjectProjectIdInferenceInferenceIdEvaluationEvaluationIdImport } from './routes/_authed/dashboard/project/$projectId/inference/$inferenceId/evaluation/$evaluationId'

// Create/Update Routes

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const AuthedRoute = AuthedImport.update({
  id: '/_authed',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AuthedDashboardRoute = AuthedDashboardImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthedRoute,
} as any)

const AuthedDashboardIndexRoute = AuthedDashboardIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedDashboardRoute,
} as any)

const AuthedDashboardSettingsRoute = AuthedDashboardSettingsImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthedDashboardRoute,
} as any)

const AuthedDashboardProjectIndexRoute =
  AuthedDashboardProjectIndexImport.update({
    id: '/project/',
    path: '/project/',
    getParentRoute: () => AuthedDashboardRoute,
  } as any)

const AuthedDashboardDatasetIndexRoute =
  AuthedDashboardDatasetIndexImport.update({
    id: '/dataset/',
    path: '/dataset/',
    getParentRoute: () => AuthedDashboardRoute,
  } as any)

const AuthedDashboardProjectCreateRoute =
  AuthedDashboardProjectCreateImport.update({
    id: '/project/create',
    path: '/project/create',
    getParentRoute: () => AuthedDashboardRoute,
  } as any)

const AuthedDashboardProjectProjectIdRoute =
  AuthedDashboardProjectProjectIdImport.update({
    id: '/project/$projectId',
    path: '/project/$projectId',
    getParentRoute: () => AuthedDashboardRoute,
  } as any)

const AuthedDashboardDatasetCreateRoute =
  AuthedDashboardDatasetCreateImport.update({
    id: '/dataset/create',
    path: '/dataset/create',
    getParentRoute: () => AuthedDashboardRoute,
  } as any)

const AuthedDashboardDatasetDatasetIdRoute =
  AuthedDashboardDatasetDatasetIdImport.update({
    id: '/dataset/$datasetId',
    path: '/dataset/$datasetId',
    getParentRoute: () => AuthedDashboardRoute,
  } as any)

const AuthedDashboardProjectProjectIdIndexRoute =
  AuthedDashboardProjectProjectIdIndexImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthedDashboardProjectProjectIdRoute,
  } as any)

const AuthedDashboardProjectProjectIdCompareRoute =
  AuthedDashboardProjectProjectIdCompareImport.update({
    id: '/compare',
    path: '/compare',
    getParentRoute: () => AuthedDashboardProjectProjectIdRoute,
  } as any)

const AuthedDashboardProjectProjectIdInferenceCreateRoute =
  AuthedDashboardProjectProjectIdInferenceCreateImport.update({
    id: '/inference/create',
    path: '/inference/create',
    getParentRoute: () => AuthedDashboardProjectProjectIdRoute,
  } as any)

const AuthedDashboardProjectProjectIdInferenceInferenceIdIndexRoute =
  AuthedDashboardProjectProjectIdInferenceInferenceIdIndexImport.update({
    id: '/inference/$inferenceId/',
    path: '/inference/$inferenceId/',
    getParentRoute: () => AuthedDashboardProjectProjectIdRoute,
  } as any)

const AuthedDashboardProjectProjectIdInferenceInferenceIdEvaluationIndexRoute =
  AuthedDashboardProjectProjectIdInferenceInferenceIdEvaluationIndexImport.update(
    {
      id: '/inference/$inferenceId/evaluation/',
      path: '/inference/$inferenceId/evaluation/',
      getParentRoute: () => AuthedDashboardProjectProjectIdRoute,
    } as any,
  )

const AuthedDashboardProjectProjectIdInferenceInferenceIdEvaluationEvaluationIdRoute =
  AuthedDashboardProjectProjectIdInferenceInferenceIdEvaluationEvaluationIdImport.update(
    {
      id: '/inference/$inferenceId/evaluation/$evaluationId',
      path: '/inference/$inferenceId/evaluation/$evaluationId',
      getParentRoute: () => AuthedDashboardProjectProjectIdRoute,
    } as any,
  )

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthedImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/_authed/dashboard': {
      id: '/_authed/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthedDashboardImport
      parentRoute: typeof AuthedImport
    }
    '/_authed/dashboard/settings': {
      id: '/_authed/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof AuthedDashboardSettingsImport
      parentRoute: typeof AuthedDashboardImport
    }
    '/_authed/dashboard/': {
      id: '/_authed/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthedDashboardIndexImport
      parentRoute: typeof AuthedDashboardImport
    }
    '/_authed/dashboard/dataset/$datasetId': {
      id: '/_authed/dashboard/dataset/$datasetId'
      path: '/dataset/$datasetId'
      fullPath: '/dashboard/dataset/$datasetId'
      preLoaderRoute: typeof AuthedDashboardDatasetDatasetIdImport
      parentRoute: typeof AuthedDashboardImport
    }
    '/_authed/dashboard/dataset/create': {
      id: '/_authed/dashboard/dataset/create'
      path: '/dataset/create'
      fullPath: '/dashboard/dataset/create'
      preLoaderRoute: typeof AuthedDashboardDatasetCreateImport
      parentRoute: typeof AuthedDashboardImport
    }
    '/_authed/dashboard/project/$projectId': {
      id: '/_authed/dashboard/project/$projectId'
      path: '/project/$projectId'
      fullPath: '/dashboard/project/$projectId'
      preLoaderRoute: typeof AuthedDashboardProjectProjectIdImport
      parentRoute: typeof AuthedDashboardImport
    }
    '/_authed/dashboard/project/create': {
      id: '/_authed/dashboard/project/create'
      path: '/project/create'
      fullPath: '/dashboard/project/create'
      preLoaderRoute: typeof AuthedDashboardProjectCreateImport
      parentRoute: typeof AuthedDashboardImport
    }
    '/_authed/dashboard/dataset/': {
      id: '/_authed/dashboard/dataset/'
      path: '/dataset'
      fullPath: '/dashboard/dataset'
      preLoaderRoute: typeof AuthedDashboardDatasetIndexImport
      parentRoute: typeof AuthedDashboardImport
    }
    '/_authed/dashboard/project/': {
      id: '/_authed/dashboard/project/'
      path: '/project'
      fullPath: '/dashboard/project'
      preLoaderRoute: typeof AuthedDashboardProjectIndexImport
      parentRoute: typeof AuthedDashboardImport
    }
    '/_authed/dashboard/project/$projectId/compare': {
      id: '/_authed/dashboard/project/$projectId/compare'
      path: '/compare'
      fullPath: '/dashboard/project/$projectId/compare'
      preLoaderRoute: typeof AuthedDashboardProjectProjectIdCompareImport
      parentRoute: typeof AuthedDashboardProjectProjectIdImport
    }
    '/_authed/dashboard/project/$projectId/': {
      id: '/_authed/dashboard/project/$projectId/'
      path: '/'
      fullPath: '/dashboard/project/$projectId/'
      preLoaderRoute: typeof AuthedDashboardProjectProjectIdIndexImport
      parentRoute: typeof AuthedDashboardProjectProjectIdImport
    }
    '/_authed/dashboard/project/$projectId/inference/create': {
      id: '/_authed/dashboard/project/$projectId/inference/create'
      path: '/inference/create'
      fullPath: '/dashboard/project/$projectId/inference/create'
      preLoaderRoute: typeof AuthedDashboardProjectProjectIdInferenceCreateImport
      parentRoute: typeof AuthedDashboardProjectProjectIdImport
    }
    '/_authed/dashboard/project/$projectId/inference/$inferenceId/': {
      id: '/_authed/dashboard/project/$projectId/inference/$inferenceId/'
      path: '/inference/$inferenceId'
      fullPath: '/dashboard/project/$projectId/inference/$inferenceId'
      preLoaderRoute: typeof AuthedDashboardProjectProjectIdInferenceInferenceIdIndexImport
      parentRoute: typeof AuthedDashboardProjectProjectIdImport
    }
    '/_authed/dashboard/project/$projectId/inference/$inferenceId/evaluation/$evaluationId': {
      id: '/_authed/dashboard/project/$projectId/inference/$inferenceId/evaluation/$evaluationId'
      path: '/inference/$inferenceId/evaluation/$evaluationId'
      fullPath: '/dashboard/project/$projectId/inference/$inferenceId/evaluation/$evaluationId'
      preLoaderRoute: typeof AuthedDashboardProjectProjectIdInferenceInferenceIdEvaluationEvaluationIdImport
      parentRoute: typeof AuthedDashboardProjectProjectIdImport
    }
    '/_authed/dashboard/project/$projectId/inference/$inferenceId/evaluation/': {
      id: '/_authed/dashboard/project/$projectId/inference/$inferenceId/evaluation/'
      path: '/inference/$inferenceId/evaluation'
      fullPath: '/dashboard/project/$projectId/inference/$inferenceId/evaluation'
      preLoaderRoute: typeof AuthedDashboardProjectProjectIdInferenceInferenceIdEvaluationIndexImport
      parentRoute: typeof AuthedDashboardProjectProjectIdImport
    }
  }
}

// Create and export the route tree

interface AuthedDashboardProjectProjectIdRouteChildren {
  AuthedDashboardProjectProjectIdCompareRoute: typeof AuthedDashboardProjectProjectIdCompareRoute
  AuthedDashboardProjectProjectIdIndexRoute: typeof AuthedDashboardProjectProjectIdIndexRoute
  AuthedDashboardProjectProjectIdInferenceCreateRoute: typeof AuthedDashboardProjectProjectIdInferenceCreateRoute
  AuthedDashboardProjectProjectIdInferenceInferenceIdIndexRoute: typeof AuthedDashboardProjectProjectIdInferenceInferenceIdIndexRoute
  AuthedDashboardProjectProjectIdInferenceInferenceIdEvaluationEvaluationIdRoute: typeof AuthedDashboardProjectProjectIdInferenceInferenceIdEvaluationEvaluationIdRoute
  AuthedDashboardProjectProjectIdInferenceInferenceIdEvaluationIndexRoute: typeof AuthedDashboardProjectProjectIdInferenceInferenceIdEvaluationIndexRoute
}

const AuthedDashboardProjectProjectIdRouteChildren: AuthedDashboardProjectProjectIdRouteChildren =
  {
    AuthedDashboardProjectProjectIdCompareRoute:
      AuthedDashboardProjectProjectIdCompareRoute,
    AuthedDashboardProjectProjectIdIndexRoute:
      AuthedDashboardProjectProjectIdIndexRoute,
    AuthedDashboardProjectProjectIdInferenceCreateRoute:
      AuthedDashboardProjectProjectIdInferenceCreateRoute,
    AuthedDashboardProjectProjectIdInferenceInferenceIdIndexRoute:
      AuthedDashboardProjectProjectIdInferenceInferenceIdIndexRoute,
    AuthedDashboardProjectProjectIdInferenceInferenceIdEvaluationEvaluationIdRoute:
      AuthedDashboardProjectProjectIdInferenceInferenceIdEvaluationEvaluationIdRoute,
    AuthedDashboardProjectProjectIdInferenceInferenceIdEvaluationIndexRoute:
      AuthedDashboardProjectProjectIdInferenceInferenceIdEvaluationIndexRoute,
  }

const AuthedDashboardProjectProjectIdRouteWithChildren =
  AuthedDashboardProjectProjectIdRoute._addFileChildren(
    AuthedDashboardProjectProjectIdRouteChildren,
  )

interface AuthedDashboardRouteChildren {
  AuthedDashboardSettingsRoute: typeof AuthedDashboardSettingsRoute
  AuthedDashboardIndexRoute: typeof AuthedDashboardIndexRoute
  AuthedDashboardDatasetDatasetIdRoute: typeof AuthedDashboardDatasetDatasetIdRoute
  AuthedDashboardDatasetCreateRoute: typeof AuthedDashboardDatasetCreateRoute
  AuthedDashboardProjectProjectIdRoute: typeof AuthedDashboardProjectProjectIdRouteWithChildren
  AuthedDashboardProjectCreateRoute: typeof AuthedDashboardProjectCreateRoute
  AuthedDashboardDatasetIndexRoute: typeof AuthedDashboardDatasetIndexRoute
  AuthedDashboardProjectIndexRoute: typeof AuthedDashboardProjectIndexRoute
}

const AuthedDashboardRouteChildren: AuthedDashboardRouteChildren = {
  AuthedDashboardSettingsRoute: AuthedDashboardSettingsRoute,
  AuthedDashboardIndexRoute: AuthedDashboardIndexRoute,
  AuthedDashboardDatasetDatasetIdRoute: AuthedDashboardDatasetDatasetIdRoute,
  AuthedDashboardDatasetCreateRoute: AuthedDashboardDatasetCreateRoute,
  AuthedDashboardProjectProjectIdRoute:
    AuthedDashboardProjectProjectIdRouteWithChildren,
  AuthedDashboardProjectCreateRoute: AuthedDashboardProjectCreateRoute,
  AuthedDashboardDatasetIndexRoute: AuthedDashboardDatasetIndexRoute,
  AuthedDashboardProjectIndexRoute: AuthedDashboardProjectIndexRoute,
}

const AuthedDashboardRouteWithChildren = AuthedDashboardRoute._addFileChildren(
  AuthedDashboardRouteChildren,
)

interface AuthedRouteChildren {
  AuthedDashboardRoute: typeof AuthedDashboardRouteWithChildren
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedDashboardRoute: AuthedDashboardRouteWithChildren,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthedDashboardRouteWithChildren
  '/dashboard/settings': typeof AuthedDashboardSettingsRoute
  '/dashboard/': typeof AuthedDashboardIndexRoute
  '/dashboard/dataset/$datasetId': typeof AuthedDashboardDatasetDatasetIdRoute
  '/dashboard/dataset/create': typeof AuthedDashboardDatasetCreateRoute
  '/dashboard/project/$projectId': typeof AuthedDashboardProjectProjectIdRouteWithChildren
  '/dashboard/project/create': typeof AuthedDashboardProjectCreateRoute
  '/dashboard/dataset': typeof AuthedDashboardDatasetIndexRoute
  '/dashboard/project': typeof AuthedDashboardProjectIndexRoute
  '/dashboard/project/$projectId/compare': typeof AuthedDashboardProjectProjectIdCompareRoute
  '/dashboard/project/$projectId/': typeof AuthedDashboardProjectProjectIdIndexRoute
  '/dashboard/project/$projectId/inference/create': typeof AuthedDashboardProjectProjectIdInferenceCreateRoute
  '/dashboard/project/$projectId/inference/$inferenceId': typeof AuthedDashboardProjectProjectIdInferenceInferenceIdIndexRoute
  '/dashboard/project/$projectId/inference/$inferenceId/evaluation/$evaluationId': typeof AuthedDashboardProjectProjectIdInferenceInferenceIdEvaluationEvaluationIdRoute
  '/dashboard/project/$projectId/inference/$inferenceId/evaluation': typeof AuthedDashboardProjectProjectIdInferenceInferenceIdEvaluationIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/dashboard/settings': typeof AuthedDashboardSettingsRoute
  '/dashboard': typeof AuthedDashboardIndexRoute
  '/dashboard/dataset/$datasetId': typeof AuthedDashboardDatasetDatasetIdRoute
  '/dashboard/dataset/create': typeof AuthedDashboardDatasetCreateRoute
  '/dashboard/project/create': typeof AuthedDashboardProjectCreateRoute
  '/dashboard/dataset': typeof AuthedDashboardDatasetIndexRoute
  '/dashboard/project': typeof AuthedDashboardProjectIndexRoute
  '/dashboard/project/$projectId/compare': typeof AuthedDashboardProjectProjectIdCompareRoute
  '/dashboard/project/$projectId': typeof AuthedDashboardProjectProjectIdIndexRoute
  '/dashboard/project/$projectId/inference/create': typeof AuthedDashboardProjectProjectIdInferenceCreateRoute
  '/dashboard/project/$projectId/inference/$inferenceId': typeof AuthedDashboardProjectProjectIdInferenceInferenceIdIndexRoute
  '/dashboard/project/$projectId/inference/$inferenceId/evaluation/$evaluationId': typeof AuthedDashboardProjectProjectIdInferenceInferenceIdEvaluationEvaluationIdRoute
  '/dashboard/project/$projectId/inference/$inferenceId/evaluation': typeof AuthedDashboardProjectProjectIdInferenceInferenceIdEvaluationIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authed/dashboard': typeof AuthedDashboardRouteWithChildren
  '/_authed/dashboard/settings': typeof AuthedDashboardSettingsRoute
  '/_authed/dashboard/': typeof AuthedDashboardIndexRoute
  '/_authed/dashboard/dataset/$datasetId': typeof AuthedDashboardDatasetDatasetIdRoute
  '/_authed/dashboard/dataset/create': typeof AuthedDashboardDatasetCreateRoute
  '/_authed/dashboard/project/$projectId': typeof AuthedDashboardProjectProjectIdRouteWithChildren
  '/_authed/dashboard/project/create': typeof AuthedDashboardProjectCreateRoute
  '/_authed/dashboard/dataset/': typeof AuthedDashboardDatasetIndexRoute
  '/_authed/dashboard/project/': typeof AuthedDashboardProjectIndexRoute
  '/_authed/dashboard/project/$projectId/compare': typeof AuthedDashboardProjectProjectIdCompareRoute
  '/_authed/dashboard/project/$projectId/': typeof AuthedDashboardProjectProjectIdIndexRoute
  '/_authed/dashboard/project/$projectId/inference/create': typeof AuthedDashboardProjectProjectIdInferenceCreateRoute
  '/_authed/dashboard/project/$projectId/inference/$inferenceId/': typeof AuthedDashboardProjectProjectIdInferenceInferenceIdIndexRoute
  '/_authed/dashboard/project/$projectId/inference/$inferenceId/evaluation/$evaluationId': typeof AuthedDashboardProjectProjectIdInferenceInferenceIdEvaluationEvaluationIdRoute
  '/_authed/dashboard/project/$projectId/inference/$inferenceId/evaluation/': typeof AuthedDashboardProjectProjectIdInferenceInferenceIdEvaluationIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | ''
    | '/login'
    | '/dashboard'
    | '/dashboard/settings'
    | '/dashboard/'
    | '/dashboard/dataset/$datasetId'
    | '/dashboard/dataset/create'
    | '/dashboard/project/$projectId'
    | '/dashboard/project/create'
    | '/dashboard/dataset'
    | '/dashboard/project'
    | '/dashboard/project/$projectId/compare'
    | '/dashboard/project/$projectId/'
    | '/dashboard/project/$projectId/inference/create'
    | '/dashboard/project/$projectId/inference/$inferenceId'
    | '/dashboard/project/$projectId/inference/$inferenceId/evaluation/$evaluationId'
    | '/dashboard/project/$projectId/inference/$inferenceId/evaluation'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | ''
    | '/login'
    | '/dashboard/settings'
    | '/dashboard'
    | '/dashboard/dataset/$datasetId'
    | '/dashboard/dataset/create'
    | '/dashboard/project/create'
    | '/dashboard/dataset'
    | '/dashboard/project'
    | '/dashboard/project/$projectId/compare'
    | '/dashboard/project/$projectId'
    | '/dashboard/project/$projectId/inference/create'
    | '/dashboard/project/$projectId/inference/$inferenceId'
    | '/dashboard/project/$projectId/inference/$inferenceId/evaluation/$evaluationId'
    | '/dashboard/project/$projectId/inference/$inferenceId/evaluation'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/login'
    | '/_authed/dashboard'
    | '/_authed/dashboard/settings'
    | '/_authed/dashboard/'
    | '/_authed/dashboard/dataset/$datasetId'
    | '/_authed/dashboard/dataset/create'
    | '/_authed/dashboard/project/$projectId'
    | '/_authed/dashboard/project/create'
    | '/_authed/dashboard/dataset/'
    | '/_authed/dashboard/project/'
    | '/_authed/dashboard/project/$projectId/compare'
    | '/_authed/dashboard/project/$projectId/'
    | '/_authed/dashboard/project/$projectId/inference/create'
    | '/_authed/dashboard/project/$projectId/inference/$inferenceId/'
    | '/_authed/dashboard/project/$projectId/inference/$inferenceId/evaluation/$evaluationId'
    | '/_authed/dashboard/project/$projectId/inference/$inferenceId/evaluation/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  LoginRoute: LoginRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_authed",
        "/login"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_authed": {
      "filePath": "_authed.tsx",
      "children": [
        "/_authed/dashboard"
      ]
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/_authed/dashboard": {
      "filePath": "_authed/dashboard.tsx",
      "parent": "/_authed",
      "children": [
        "/_authed/dashboard/settings",
        "/_authed/dashboard/",
        "/_authed/dashboard/dataset/$datasetId",
        "/_authed/dashboard/dataset/create",
        "/_authed/dashboard/project/$projectId",
        "/_authed/dashboard/project/create",
        "/_authed/dashboard/dataset/",
        "/_authed/dashboard/project/"
      ]
    },
    "/_authed/dashboard/settings": {
      "filePath": "_authed/dashboard/settings.tsx",
      "parent": "/_authed/dashboard"
    },
    "/_authed/dashboard/": {
      "filePath": "_authed/dashboard/index.tsx",
      "parent": "/_authed/dashboard"
    },
    "/_authed/dashboard/dataset/$datasetId": {
      "filePath": "_authed/dashboard/dataset/$datasetId.tsx",
      "parent": "/_authed/dashboard"
    },
    "/_authed/dashboard/dataset/create": {
      "filePath": "_authed/dashboard/dataset/create.tsx",
      "parent": "/_authed/dashboard"
    },
    "/_authed/dashboard/project/$projectId": {
      "filePath": "_authed/dashboard/project/$projectId.tsx",
      "parent": "/_authed/dashboard",
      "children": [
        "/_authed/dashboard/project/$projectId/compare",
        "/_authed/dashboard/project/$projectId/",
        "/_authed/dashboard/project/$projectId/inference/create",
        "/_authed/dashboard/project/$projectId/inference/$inferenceId/",
        "/_authed/dashboard/project/$projectId/inference/$inferenceId/evaluation/$evaluationId",
        "/_authed/dashboard/project/$projectId/inference/$inferenceId/evaluation/"
      ]
    },
    "/_authed/dashboard/project/create": {
      "filePath": "_authed/dashboard/project/create.tsx",
      "parent": "/_authed/dashboard"
    },
    "/_authed/dashboard/dataset/": {
      "filePath": "_authed/dashboard/dataset/index.tsx",
      "parent": "/_authed/dashboard"
    },
    "/_authed/dashboard/project/": {
      "filePath": "_authed/dashboard/project/index.tsx",
      "parent": "/_authed/dashboard"
    },
    "/_authed/dashboard/project/$projectId/compare": {
      "filePath": "_authed/dashboard/project/$projectId/compare.tsx",
      "parent": "/_authed/dashboard/project/$projectId"
    },
    "/_authed/dashboard/project/$projectId/": {
      "filePath": "_authed/dashboard/project/$projectId/index.tsx",
      "parent": "/_authed/dashboard/project/$projectId"
    },
    "/_authed/dashboard/project/$projectId/inference/create": {
      "filePath": "_authed/dashboard/project/$projectId/inference/create.tsx",
      "parent": "/_authed/dashboard/project/$projectId"
    },
    "/_authed/dashboard/project/$projectId/inference/$inferenceId/": {
      "filePath": "_authed/dashboard/project/$projectId/inference/$inferenceId/index.tsx",
      "parent": "/_authed/dashboard/project/$projectId"
    },
    "/_authed/dashboard/project/$projectId/inference/$inferenceId/evaluation/$evaluationId": {
      "filePath": "_authed/dashboard/project/$projectId/inference/$inferenceId/evaluation/$evaluationId.tsx",
      "parent": "/_authed/dashboard/project/$projectId"
    },
    "/_authed/dashboard/project/$projectId/inference/$inferenceId/evaluation/": {
      "filePath": "_authed/dashboard/project/$projectId/inference/$inferenceId/evaluation/index.tsx",
      "parent": "/_authed/dashboard/project/$projectId"
    }
  }
}
ROUTE_MANIFEST_END */
